### ISSUE TITLE
Adding topology to openvino

### ISSUE THREAD

**Issue by likholat** [likholat/open_model_zoo#2]
### Adding
1. For ```/opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader``` add ```__init__.py```:
    ```python
    #__init__.py
    from .topologies import *
    ```
2. For ```topology.py```, ```downloader.py``` and ```converter.py``` change imports:
    ```python
    import common -> from . import common
    import downloader -> from . import downloader
    import converter -> from . import converter
    ```
3. Create a symbolic link:
    ```bash
    ln -s /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader ~/opt/intel/openvino/python/python3.X/openvino/open_model_zoo
    ```
4. Initialize openvino enviroment variable :
    ```bash
     source /opt/intel/openvino/bin/setupvars.sh
     ```
### Usage example
```python
import openvino.open_model_zoo as omz
ssd = omz.Topology('mobilenet-ssd')

xml_path, bin_path = ssd.get_ir()
```

**Comment by likholat** [comment]
@dkurt

**Comment by dkurt** [comment]
Please remove the steps which already considered by the pull request (like "Add argv to main of converter.py and downloader.py:" and "Add topology.py to open_model_zoo directory").

**Comment by dkurt** [comment]
> Add folder open_model_zoo

Can you please try to create a symbolic link instead

**Comment by dkurt** [comment]
There is already `/opt/intel/openvino/deployment_tools/open_model_zoo`. So I think we can
1) Create `/opt/intel/openvino/deployment_tools/open_model_zoo/__init__` which can `import tools.topologies`
2)  `export PYTHONPATH=/opt/intel/openvino/deployment_tools/open_model_zoo/:$PYTHONPATH`

**Comment by dkurt** [comment]
Or not...
1) symbolic link `/opt/intel/openvino/python/python3.5/openvino/open_model_zoo` -> `/opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/`
2) Create `/opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/__init__.py`
